Repository Solepli/Solepli-backend, pull requests merged in 2025-05, with the labels that each got.

#21 Feat: 소셜 로그인 기능 구현 완료 (#20)
  build.gradle
  src/main/java/com/ilta/solepli/domain/auth/controller/AuthController.java
  src/main/java/com/ilta/solepli/domain/auth/dto/request/BasicLoginRequest.java
  src/main/java/com/ilta/solepli/domain/auth/dto/response/LoginResponse.java
  src/main/java/com/ilta/solepli/domain/auth/dto/response/oauth/google/GoogleTokenResponse.java
  src/main/java/com/ilta/solepli/domain/auth/dto/response/oauth/google/GoogleUserInfoResponse.java
  src/main/java/com/ilta/solepli/domain/auth/dto/response/oauth/kakao/KakaoTokenResponse.java
  src/main/java/com/ilta/solepli/domain/auth/dto/response/oauth/kakao/KakaoUserInfoResponse.java
  src/main/java/com/ilta/solepli/domain/auth/dto/response/oauth/naver/NaverTokenResponse.java
  src/main/java/com/ilta/solepli/domain/auth/dto/response/oauth/naver/NaverUserInfoResponse.java
  src/main/java/com/ilta/solepli/domain/auth/entity/LoginType.java
  src/main/java/com/ilta/solepli/domain/auth/filter/JwtAuthenticationFilter.java
  src/main/java/com/ilta/solepli/domain/auth/service/AuthService.java
  src/main/java/com/ilta/solepli/domain/auth/service/JwtTokenProvider.java
  src/main/java/com/ilta/solepli/domain/auth/service/oauth/GoogleService.java
  src/main/java/com/ilta/solepli/domain/auth/service/oauth/KakaoService.java
  src/main/java/com/ilta/solepli/domain/auth/service/oauth/NaverService.java
  src/main/java/com/ilta/solepli/domain/auth/service/oauth/OAuthService.java
  src/main/java/com/ilta/solepli/domain/auth/service/oauth/OAuthServiceFactory.java
  src/main/java/com/ilta/solepli/domain/user/entity/Role.java
  src/main/java/com/ilta/solepli/domain/user/entity/User.java
  src/main/java/com/ilta/solepli/domain/user/repository/UserRepository.java
  src/main/java/com/ilta/solepli/domain/user/service/UserService.java
  src/main/java/com/ilta/solepli/domain/user/util/CustomUserDetailService.java
  src/main/java/com/ilta/solepli/domain/user/util/CustomUserDetails.java
  src/main/java/com/ilta/solepli/global/config/CommonConfig.java
  src/main/java/com/ilta/solepli/global/config/SecurityConfig.java
  src/main/java/com/ilta/solepli/global/config/SwaggerConfig.java
  src/main/java/com/ilta/solepli/global/config/WebClientConfig.java
  src/main/java/com/ilta/solepli/global/exception/ErrorCode.java
  src/main/resources/application.yml
Labels: Feature ✨

#24 Feat: 리뷰 기능 구현 완료 #22
  build.gradle
  src/main/java/com/ilta/solepli/domain/place/entity/Place.java
  src/main/java/com/ilta/solepli/domain/place/repository/PlaceRepository.java
  src/main/java/com/ilta/solepli/domain/review/controller/ReviewController.java
  src/main/java/com/ilta/solepli/domain/review/dto/request/ReviewCreateRequest.java
  src/main/java/com/ilta/solepli/domain/review/entity/Review.java
  src/main/java/com/ilta/solepli/domain/review/entity/mapping/ReviewImage.java
  src/main/java/com/ilta/solepli/domain/review/entity/mapping/ReviewTag.java
  src/main/java/com/ilta/solepli/domain/review/repository/ReviewRepository.java
  src/main/java/com/ilta/solepli/domain/review/service/ReviewService.java
  src/main/java/com/ilta/solepli/domain/sollect/entity/Sollect.java
  src/main/java/com/ilta/solepli/domain/sollect/entity/SollectContent.java
  src/main/java/com/ilta/solepli/domain/sollect/entity/SollectType.java
  src/main/java/com/ilta/solepli/domain/sollect/entity/mapping/SollectPlace.java
  src/main/java/com/ilta/solepli/domain/tag/entity/MoodTag.java
  src/main/java/com/ilta/solepli/domain/tag/entity/SoloTag.java
  src/main/java/com/ilta/solepli/domain/tag/entity/TagType.java
  src/main/java/com/ilta/solepli/domain/user/service/UserService.java
  src/main/java/com/ilta/solepli/global/config/S3Config.java
  src/main/java/com/ilta/solepli/global/exception/ErrorCode.java
  src/main/java/com/ilta/solepli/global/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/ilta/solepli/global/service/S3Service.java
  src/main/resources/application.yml
Labels: Feature ✨

#25 Feat: 지도화면 내 장소 마커 데이터 조회 API 구현 (#23)
  src/main/java/com/ilta/solepli/domain/category/repository/CategoryRepository.java
  src/main/java/com/ilta/solepli/domain/place/entity/Place.java
  src/main/java/com/ilta/solepli/domain/place/repository/PlaceRepository.java
  src/main/java/com/ilta/solepli/domain/solemap/controller/SolemapController.java
  src/main/java/com/ilta/solepli/domain/solemap/dto/ViewportMapMarkerDetail.java
  src/main/java/com/ilta/solepli/domain/solemap/dto/ViewportMapMarkerResponse.java
  src/main/java/com/ilta/solepli/domain/solemap/service/SolemapService.java
  src/main/java/com/ilta/solepli/global/config/SecurityConfig.java
  src/main/java/com/ilta/solepli/global/exception/ErrorCode.java
Labels: Feature ✨

#27 Feat: 쏠렉트 등록 기능 구현 (#26)
  src/main/java/com/ilta/solepli/domain/solelect/controller/SolelectController.java
  src/main/java/com/ilta/solepli/domain/solelect/dto/request/SolelectCreateRequest.java
  src/main/java/com/ilta/solepli/domain/solelect/dto/response/SolelectCreateResponse.java
  src/main/java/com/ilta/solepli/domain/solelect/entity/ContentType.java
  src/main/java/com/ilta/solepli/domain/solelect/entity/Solelect.java
  src/main/java/com/ilta/solepli/domain/solelect/entity/SolelectContent.java
  src/main/java/com/ilta/solepli/domain/solelect/entity/mapping/SolelectPlace.java
  src/main/java/com/ilta/solepli/domain/solelect/repository/SolelectContentRepository.java
  src/main/java/com/ilta/solepli/domain/solelect/repository/SolelectPlaceRepository.java
  src/main/java/com/ilta/solepli/domain/solelect/repository/SolelectRepository.java
  src/main/java/com/ilta/solepli/domain/solelect/service/SolelectService.java
  src/main/java/com/ilta/solepli/domain/sollect/entity/SollectType.java
  src/main/java/com/ilta/solepli/global/exception/ErrorCode.java
  src/main/java/com/ilta/solepli/global/service/S3Service.java
Labels: Feature ✨

#29 Feat: 쏠렉트 수정 및 삭제 기능 구현 (#26)
  src/main/java/com/ilta/solepli/domain/review/service/ReviewService.java
  src/main/java/com/ilta/solepli/domain/solelect/controller/SolelectController.java
  src/main/java/com/ilta/solepli/domain/solelect/dto/request/SolelectUpdateRequest.java
  src/main/java/com/ilta/solepli/domain/solelect/entity/Solelect.java
  src/main/java/com/ilta/solepli/domain/solelect/entity/SolelectContent.java
  src/main/java/com/ilta/solepli/domain/solelect/entity/mapping/SolelectPlace.java
  src/main/java/com/ilta/solepli/domain/solelect/repository/SolelectContentRepository.java
  src/main/java/com/ilta/solepli/domain/solelect/repository/SolelectPlaceRepository.java
  src/main/java/com/ilta/solepli/domain/solelect/repository/SolelectRepository.java
  src/main/java/com/ilta/solepli/domain/solelect/service/SolelectService.java
  src/main/java/com/ilta/solepli/global/exception/ErrorCode.java
  src/main/java/com/ilta/solepli/global/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/ilta/solepli/global/service/S3Service.java
  src/main/resources/application.yml
Labels: Feature ✨, Refactor ♻️

#31 Refactor: 쏠렉트 삭제 방식 SoftDelete으로 변경으로 인한 쿼리 수정 (#26)
  src/main/java/com/ilta/solepli/domain/solelect/repository/SolelectRepository.java
Labels: Refactor ♻️

#30 Feat: 최근 검색어 기능 구현 (#28)
  Dockerfile
  build.gradle
  docker-compose.yml
  src/main/java/com/ilta/solepli/domain/solemap/controller/SolemapController.java
  src/main/java/com/ilta/solepli/domain/solemap/dto/KeywordRequest.java
  src/main/java/com/ilta/solepli/domain/solemap/service/SolemapService.java
  src/main/java/com/ilta/solepli/global/config/RedisConfig.java
  src/main/java/com/ilta/solepli/global/config/RedisProperties.java
  src/main/java/com/ilta/solepli/global/exception/ErrorCode.java
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: Feature ✨

#33 Chore: CORS 설정 주소, 쏠맵, 쏠렉트의 이름을 변경한다 (#32)
  docker-compose.yml
  src/main/java/com/ilta/solepli/domain/solelect/dto/request/SolelectCreateRequest.java
  src/main/java/com/ilta/solepli/domain/solelect/dto/request/SolelectUpdateRequest.java
  src/main/java/com/ilta/solepli/domain/solelect/dto/response/SolelectCreateResponse.java
  src/main/java/com/ilta/solepli/domain/solelect/entity/ContentType.java
  src/main/java/com/ilta/solepli/domain/solelect/repository/SolelectContentRepository.java
  src/main/java/com/ilta/solepli/domain/solelect/repository/SolelectPlaceRepository.java
  src/main/java/com/ilta/solepli/domain/solelect/repository/SolelectRepository.java
  src/main/java/com/ilta/solepli/domain/solelect/service/SolelectService.java
  src/main/java/com/ilta/solepli/domain/sollect/controller/SollectController.java
  src/main/java/com/ilta/solepli/domain/sollect/dto/request/SollectCreateRequest.java
  src/main/java/com/ilta/solepli/domain/sollect/dto/request/SollectUpdateRequest.java
  src/main/java/com/ilta/solepli/domain/sollect/dto/response/SollectCreateResponse.java
  src/main/java/com/ilta/solepli/domain/sollect/entity/ContentType.java
  src/main/java/com/ilta/solepli/domain/sollect/entity/Sollect.java
  src/main/java/com/ilta/solepli/domain/sollect/entity/SollectContent.java
  src/main/java/com/ilta/solepli/domain/sollect/entity/mapping/SollectPlace.java
  src/main/java/com/ilta/solepli/domain/sollect/repository/SollectContentRepository.java
  src/main/java/com/ilta/solepli/domain/sollect/repository/SollectPlaceRepository.java
  src/main/java/com/ilta/solepli/domain/sollect/repository/SollectRepository.java
  src/main/java/com/ilta/solepli/domain/sollect/service/SollectService.java
  src/main/java/com/ilta/solepli/domain/solmap/controller/SolmapController.java
  src/main/java/com/ilta/solepli/domain/solmap/dto/KeywordRequest.java
  src/main/java/com/ilta/solepli/domain/solmap/dto/ViewportMapMarkerDetail.java
  src/main/java/com/ilta/solepli/domain/solmap/dto/ViewportMapMarkerResponse.java
  src/main/java/com/ilta/solepli/domain/solmap/service/SolmapService.java
  src/main/java/com/ilta/solepli/global/config/SecurityConfig.java
  src/main/java/com/ilta/solepli/global/exception/ErrorCode.java
  src/main/java/com/ilta/solepli/global/service/S3Service.java
Labels: Chore ⚙️

#38 Feat: 지도 화면 내 선택된 카테고리별 장소 리스트 조회 API 구현
  src/main/java/com/ilta/solepli/domain/place/entity/Place.java
  src/main/java/com/ilta/solepli/domain/place/repository/PlaceRepository.java
  src/main/java/com/ilta/solepli/domain/place/repository/PlaceRepositoryCustom.java
  src/main/java/com/ilta/solepli/domain/place/repository/PlaceRepositoryImpl.java
  src/main/java/com/ilta/solepli/domain/solmap/controller/SolmapController.java
  src/main/java/com/ilta/solepli/domain/solmap/dto/PlacePreviewDetail.java
  src/main/java/com/ilta/solepli/domain/solmap/dto/PlaceSearchPreviewResponse.java
  src/main/java/com/ilta/solepli/domain/solmap/dto/ViewportMapMarkerResponse.java
  src/main/java/com/ilta/solepli/domain/solmap/service/SolmapService.java
  src/main/java/com/ilta/solepli/global/config/SecurityConfig.java
  src/main/java/com/ilta/solepli/global/dto/OpenStatus.java
  src/main/java/com/ilta/solepli/global/util/OpenStatusUtil.java
Labels: Feature ✨
