Repository Solepli/Solepli-backend, pull requests merged in 2025-04, with the labels that each got.

#3 Chore: CI/CD 파이프라인 및 서버 인프라 구축 완료
  .github/workflows/solpli-be-dev-cd.yml
  .github/workflows/solpli-be-dev-ci.yml
  Dockerfile
  build.gradle
  docker-compose.yml
  src/main/java/com/ilta/solpli/global/HealthCheck.java
  src/main/resources/application.yml
Labels: Chore ⚙️, Database 🗃️, Infrastructure 🌎

#4 Test: CI/CD 테스트2
  src/main/java/com/ilta/solpli/global/HealthCheck.java
Labels: Test ✅

#5 Test: CI/CD 테스트3 (#2)
  src/main/java/com/ilta/solpli/global/HealthCheck.java
Labels: Test ✅

#6 Test: CI/CD 테스트4 (#2)
  src/main/java/com/ilta/solpli/global/HealthCheck.java
Labels: Test ✅

#7 Test: CI/CD 테스트5 (#2)
  src/main/java/com/ilta/solpli/global/HealthCheck.java
Labels: Test ✅

#8 Test: CI/CD 테스트 6 #2
  src/main/java/com/ilta/solpli/global/HealthCheck.java
  src/main/resources/application.yml
Labels: Test ✅

#9 Test: CI/CD 테스트 7 (#2)
  src/main/java/com/ilta/solpli/global/HealthCheck.java
Labels: Test ✅

#10 Test: CI/CD 테스트 8 (#2)
  src/main/java/com/ilta/solpli/global/HealthCheck.java
Labels: Test ✅

#13 [Feat] 공통 엔티티, 예외 처리, 응답 코드 구현
  src/main/java/com/ilta/solpli/SolpliApplication.java
  src/main/java/com/ilta/solpli/global/HealthCheck.java
  src/main/java/com/ilta/solpli/global/entity/Timestamped.java
  src/main/java/com/ilta/solpli/global/exception/CustomException.java
  src/main/java/com/ilta/solpli/global/exception/ErrorCode.java
  src/main/java/com/ilta/solpli/global/exception/InvalidRequestException.java
  src/main/java/com/ilta/solpli/global/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/ilta/solpli/global/response/ErrorResponse.java
  src/main/java/com/ilta/solpli/global/response/SuccessResponse.java
  src/test/java/com/ilta/solpli/SolpliApplicationTests.java
Labels: Feature ✨

#19 Feat: DB 구축을 위한 엔티티 생성완료 (#18)
  src/main/java/com/ilta/solepli/domain/category/entity/Category.java
  src/main/java/com/ilta/solepli/domain/place/entity/Place.java
  src/main/java/com/ilta/solepli/domain/place/entity/PlaceHour.java
  src/main/java/com/ilta/solepli/domain/place/entity/mapping/PlaceCategory.java
Labels: Feature ✨
