Repository Solepli/Solepli-backend, pull requests merged in 2025-06, with the labels that each got.

#52 Feat: 장소 상세 정보 조회 기능 구현
  src/main/java/com/ilta/solepli/domain/place/repository/PlaceRepository.java
  src/main/java/com/ilta/solepli/domain/place/repository/PlaceRepositoryImpl.java
  src/main/java/com/ilta/solepli/domain/review/entity/Review.java
  src/main/java/com/ilta/solepli/domain/review/repository/ReviewRepository.java
  src/main/java/com/ilta/solepli/domain/review/repository/ReviewTagCustomRepository.java
  src/main/java/com/ilta/solepli/domain/solmap/controller/SolmapController.java
  src/main/java/com/ilta/solepli/domain/solmap/dto/OpeningHour.java
  src/main/java/com/ilta/solepli/domain/solmap/dto/PlaceDetail.java
  src/main/java/com/ilta/solepli/domain/solmap/dto/PlaceDetailSearchResponse.java
  src/main/java/com/ilta/solepli/domain/solmap/dto/PlaceTags.java
  src/main/java/com/ilta/solepli/domain/solmap/dto/ReviewDetail.java
  src/main/java/com/ilta/solepli/domain/solmap/dto/TagInfo.java
  src/main/java/com/ilta/solepli/domain/solmap/service/SolmapService.java
  src/main/java/com/ilta/solepli/global/config/SecurityConfig.java
Labels: Feature ✨

#58 Feat: 쏠맵 연관 검색어 결과 장소 마커 정보 및 장소 프리뷰 조회 기능 구현 (#55)
  src/main/java/com/ilta/solepli/domain/place/repository/PlaceRepository.java
  src/main/java/com/ilta/solepli/domain/solmap/controller/SolmapController.java
  src/main/java/com/ilta/solepli/domain/solmap/service/SolmapService.java
Labels: Feature ✨

#60 Feat: 장소와 관련된 쏠렉트 조회 기능 구현 (#57)
  src/main/java/com/ilta/solepli/domain/sollect/controller/SollectController.java
  src/main/java/com/ilta/solepli/domain/sollect/repository/SollectPlaceRepository.java
  src/main/java/com/ilta/solepli/domain/sollect/repository/SollectRepositoryCustom.java
  src/main/java/com/ilta/solepli/domain/sollect/repository/SollectRepositoryImpl.java
  src/main/java/com/ilta/solepli/domain/sollect/service/SollectService.java
  src/main/java/com/ilta/solepli/domain/solmark/sollect/service/SolmarkSollectService.java
  src/main/java/com/ilta/solepli/global/config/SecurityConfig.java
Labels: Feature ✨

#61 Feat: 쏠맵 검색결과 없을시 주변 장소 프리뷰 조회 기능 구현 (#59)
  src/main/java/com/ilta/solepli/domain/solmap/controller/SolmapController.java
  src/main/java/com/ilta/solepli/domain/solmap/service/SolmapService.java
  src/main/java/com/ilta/solepli/global/config/SecurityConfig.java
Labels: Feature ✨, Refactor ♻️

#64 Refactor: 쏠렉트 등록 에러 해결 (#63)
  src/main/java/com/ilta/solepli/domain/sollect/entity/SollectContent.java
  src/main/java/com/ilta/solepli/domain/sollect/service/SollectService.java
Labels: Refactor ♻️

#71 Feat: 쏠렉트 상세보기 장소 요약에 장소 쏠마크 여부 추가 (#65)
  src/main/java/com/ilta/solepli/domain/sollect/controller/SollectController.java
  src/main/java/com/ilta/solepli/domain/sollect/dto/response/SollectDetailResponse.java
  src/main/java/com/ilta/solepli/domain/sollect/service/SollectService.java
Labels: Feature ✨

#72 Feat: 쏠루트 생성 기능 구현 (#69)
  src/main/java/com/ilta/solepli/domain/place/controller/PlaceController.java
  src/main/java/com/ilta/solepli/domain/place/dto/response/PlaceSearchResponse.java
  src/main/java/com/ilta/solepli/domain/place/repository/PlaceRepositoryCustom.java
  src/main/java/com/ilta/solepli/domain/place/repository/PlaceRepositoryImpl.java
  src/main/java/com/ilta/solepli/domain/place/service/PlaceService.java
  src/main/java/com/ilta/solepli/domain/sollect/controller/SollectController.java
  src/main/java/com/ilta/solepli/domain/sollect/service/SollectService.java
  src/main/java/com/ilta/solepli/domain/solroute/controller/SolrouteController.java
  src/main/java/com/ilta/solepli/domain/solroute/dto/request/SolrouteCreateRequest.java
  src/main/java/com/ilta/solepli/domain/solroute/entity/Solroute.java
  src/main/java/com/ilta/solepli/domain/solroute/entity/SolroutePlace.java
  src/main/java/com/ilta/solepli/domain/solroute/repository/SolroutePlaceRepository.java
  src/main/java/com/ilta/solepli/domain/solroute/repository/SolrouteRepository.java
  src/main/java/com/ilta/solepli/domain/solroute/service/SolrouteService.java
  src/main/java/com/ilta/solepli/global/config/SecurityConfig.java
Labels: Feature ✨, Refactor ♻️

#74 Feat: 추가한 장소 근처 인기 장소 조회 (#73)
  src/main/java/com/ilta/solepli/domain/place/repository/PlaceRepository.java
  src/main/java/com/ilta/solepli/domain/review/service/ReviewService.java
  src/main/java/com/ilta/solepli/domain/sollect/dto/response/SollectDetailResponse.java
  src/main/java/com/ilta/solepli/domain/sollect/service/SollectService.java
  src/main/java/com/ilta/solepli/domain/solroute/controller/SolrouteController.java
  src/main/java/com/ilta/solepli/domain/solroute/dto/PlaceWithReviewCountDto.java
  src/main/java/com/ilta/solepli/domain/solroute/dto/response/PlaceSummaryResponse.java
  src/main/java/com/ilta/solepli/domain/solroute/service/SolrouteService.java
  src/main/java/com/ilta/solepli/global/util/PlaceUtil.java
Labels: Feature ✨, Refactor ♻️

#76 Feat: 쏠마크 - 장소 저장 리스트 추가 기능 구현 (#75)
  src/main/java/com/ilta/solepli/domain/solmark/place/controller/SolmarkPlaceController.java
  src/main/java/com/ilta/solepli/domain/solmark/place/dto/reqeust/CreateCollectionRequest.java
  src/main/java/com/ilta/solepli/domain/solmark/place/entity/SolmarkPlaceCollection.java
  src/main/java/com/ilta/solepli/domain/solmark/place/repository/SolmarkPlaceCollectionRepository.java
  src/main/java/com/ilta/solepli/domain/solmark/place/service/SolmarkPlaceService.java
  src/main/java/com/ilta/solepli/global/exception/ErrorCode.java
Labels: Feature ✨

#80 Feat: 쏠마크 저장 리스트에 장소 추가 기능 구현 (#79)
  src/main/java/com/ilta/solepli/domain/solmark/place/controller/SolmarkPlaceController.java
  src/main/java/com/ilta/solepli/domain/solmark/place/dto/reqeust/AddSolmarkPlaceRequest.java
  src/main/java/com/ilta/solepli/domain/solmark/place/entity/SolmarkPlaceCollection.java
  src/main/java/com/ilta/solepli/domain/solmark/place/repository/SolmarkPlaceCollectionRepository.java
  src/main/java/com/ilta/solepli/domain/solmark/place/repository/SolmarkPlaceRepository.java
  src/main/java/com/ilta/solepli/domain/solmark/place/service/SolmarkPlaceService.java
  src/main/java/com/ilta/solepli/global/exception/ErrorCode.java
Labels: Feature ✨

#82 Feat: 쏠마크 - 장소 저장 리스트 조회 기능 구현 (#81)
  src/main/java/com/ilta/solepli/domain/sollect/service/SollectService.java
  src/main/java/com/ilta/solepli/domain/solmap/service/SolmapService.java
  src/main/java/com/ilta/solepli/domain/solmark/place/controller/SolmarkPlaceController.java
  src/main/java/com/ilta/solepli/domain/solmark/place/dto/response/CollectionResponse.java
  src/main/java/com/ilta/solepli/domain/solmark/place/entity/SolmarkPlace.java
  src/main/java/com/ilta/solepli/domain/solmark/place/entity/SolmarkPlaceCollection.java
  src/main/java/com/ilta/solepli/domain/solmark/place/repository/SolmarkPlaceCollectionRepository.java
  src/main/java/com/ilta/solepli/domain/solmark/place/repository/SolmarkPlaceRepository.java
  src/main/java/com/ilta/solepli/domain/solmark/place/service/SolmarkPlaceService.java
  src/main/java/com/ilta/solepli/domain/solroute/service/SolrouteService.java
Labels: Feature ✨

#87 Feat: 쏠마크 - 저장 리스트 수정 기능 구현 (#86)
  src/main/java/com/ilta/solepli/domain/solmark/place/controller/SolmarkPlaceController.java
  src/main/java/com/ilta/solepli/domain/solmark/place/dto/reqeust/UpdateCollectionRequest.java
  src/main/java/com/ilta/solepli/domain/solmark/place/entity/SolmarkPlaceCollection.java
  src/main/java/com/ilta/solepli/domain/solmark/place/repository/SolmarkPlaceCollectionRepository.java
  src/main/java/com/ilta/solepli/domain/solmark/place/service/SolmarkPlaceService.java
Labels: Feature ✨

#89 Faet: 쏠마크 저장 리스트 삭제 기능 구현 (#88)
  src/main/java/com/ilta/solepli/domain/solmark/place/controller/SolmarkPlaceController.java
  src/main/java/com/ilta/solepli/domain/solmark/place/service/SolmarkPlaceService.java
Labels: Feature ✨

#90 Feat: 추천 솔렉트 조회 기능 구현 (#83)
  src/main/java/com/ilta/solepli/domain/sollect/controller/SollectController.java
  src/main/java/com/ilta/solepli/domain/sollect/repository/SollectRepositoryCustom.java
  src/main/java/com/ilta/solepli/domain/sollect/repository/SollectRepositoryImpl.java
  src/main/java/com/ilta/solepli/domain/sollect/service/SollectService.java
  src/main/java/com/ilta/solepli/global/config/SecurityConfig.java
Labels: Feature ✨

#93 Feat: 쏠루트 코스 프리뷰 조회 기능 구현 (#92)
  src/main/java/com/ilta/solepli/domain/solroute/controller/SolrouteController.java
  src/main/java/com/ilta/solepli/domain/solroute/dto/response/SolroutePreviewResponse.java
  src/main/java/com/ilta/solepli/domain/solroute/entity/Solroute.java
  src/main/java/com/ilta/solepli/domain/solroute/entity/SolrouteStatus.java
  src/main/java/com/ilta/solepli/domain/solroute/repository/SolrouteRepository.java
  src/main/java/com/ilta/solepli/domain/solroute/service/SolrouteService.java
  src/main/java/com/ilta/solepli/global/exception/ErrorCode.java
Labels: Feature ✨

#94 Feat: 쏠마크 - 장소 추가 및 삭제 기능 구현 (#91)
  src/main/java/com/ilta/solepli/domain/solmark/place/controller/SolmarkPlaceController.java
  src/main/java/com/ilta/solepli/domain/solmark/place/dto/CollectionCountDto.java
  src/main/java/com/ilta/solepli/domain/solmark/place/dto/reqeust/AddSolmarkPlaceRequest.java
  src/main/java/com/ilta/solepli/domain/solmark/place/dto/reqeust/UpdatePlaceCollectionsRequest.java
  src/main/java/com/ilta/solepli/domain/solmark/place/repository/SolmarkPlaceCollectionRepository.java
  src/main/java/com/ilta/solepli/domain/solmark/place/repository/SolmarkPlaceRepository.java
  src/main/java/com/ilta/solepli/domain/solmark/place/service/SolmarkPlaceService.java
Labels: Feature ✨

#96 Feat: 쏠루트 코스 상세조회 기능 구현 (#95)
  src/main/java/com/ilta/solepli/domain/solroute/controller/SolrouteController.java
  src/main/java/com/ilta/solepli/domain/solroute/dto/response/SolrouteDetailResponse.java
  src/main/java/com/ilta/solepli/domain/solroute/repository/SolrouteRepository.java
  src/main/java/com/ilta/solepli/domain/solroute/service/SolrouteService.java
Labels: Feature ✨

#100 Refactor: 인증 관련 기능 리팩토링 (#99)
  src/main/java/com/ilta/solepli/domain/auth/filter/JwtAuthenticationEntryPoint.java
  src/main/java/com/ilta/solepli/domain/auth/filter/JwtAuthenticationFilter.java
  src/main/java/com/ilta/solepli/domain/auth/service/AuthService.java
  src/main/java/com/ilta/solepli/domain/auth/service/JwtTokenProvider.java
  src/main/java/com/ilta/solepli/domain/user/entity/User.java
  src/main/java/com/ilta/solepli/domain/user/service/UserService.java
  src/main/java/com/ilta/solepli/domain/user/util/CustomUserDetails.java
  src/main/java/com/ilta/solepli/global/config/SecurityConfig.java
  src/main/java/com/ilta/solepli/global/exception/ErrorCode.java
  src/main/java/com/ilta/solepli/global/exception/handler/JwtAccessDeniedHandler.java
  src/main/java/com/ilta/solepli/global/util/JwtUtil.java
  src/main/java/com/ilta/solepli/global/util/ResponseUtil.java
Labels: Refactor ♻️

#102 Fix: 쏠맵 연관 검색어 장소 조회의 스프링 시큐리티 엔드포인트 수정 (#101)
  src/main/java/com/ilta/solepli/global/config/SecurityConfig.java
Labels: Bug 🐞

#108 Refactor: HTTPS 적용으로 인한 스웨거 설정 수정 (#106)
  src/main/java/com/ilta/solepli/global/config/SwaggerConfig.java
Labels: Refactor ♻️, Security 🔒

#111 Refactor: 쏠렉트 상세조회 응답, 소셜 로그인 응답 수정 (#110)
  src/main/java/com/ilta/solepli/domain/auth/dto/response/LoginResponse.java
  src/main/java/com/ilta/solepli/domain/auth/service/AuthService.java
  src/main/java/com/ilta/solepli/domain/sollect/dto/response/SollectDetailResponse.java
  src/main/java/com/ilta/solepli/domain/sollect/service/SollectService.java
Labels: Refactor ♻️

#113 Refactor: 쏠렉트 상세조회 응답에 쏠렉트 쏠마크 여부, 쏠렉트 작성자 아이디 추가 (#112)
  src/main/java/com/ilta/solepli/domain/sollect/dto/response/SollectDetailResponse.java
  src/main/java/com/ilta/solepli/domain/sollect/service/SollectService.java
Labels: Refactor ♻️

#115 Feat: 유저 프로필 기능 구현 (#114)
  src/main/java/com/ilta/solepli/domain/profile/controller/ProfileController.java
  src/main/java/com/ilta/solepli/domain/profile/dto/request/UserProfilePatchRequest.java
  src/main/java/com/ilta/solepli/domain/profile/dto/response/UserProfileResponse.java
  src/main/java/com/ilta/solepli/domain/profile/service/ProfileService.java
  src/main/java/com/ilta/solepli/domain/profile/validator/NicknameValidator.java
  src/main/java/com/ilta/solepli/domain/user/entity/User.java
  src/main/java/com/ilta/solepli/global/config/SecurityConfig.java
  src/main/java/com/ilta/solepli/global/converter/MultipartJackson2HttpMessageConverter.java
  src/main/java/com/ilta/solepli/global/exception/ErrorCode.java
Labels: Feature ✨

#121 Fix: HttpMessageNotReadableException 처리 코드 추가 (#120)
  src/main/java/com/ilta/solepli/global/exception/handler/GlobalExceptionHandler.java
Labels: Bug 🐞, Refactor ♻️

#125 Feat: 공지사항 기능 구현 (#124)
  src/main/java/com/ilta/solepli/domain/notice/controller/NoticeController.java
  src/main/java/com/ilta/solepli/domain/notice/dto/request/NoticeCreateRequest.java
  src/main/java/com/ilta/solepli/domain/notice/dto/request/NoticeUpdateRequest.java
  src/main/java/com/ilta/solepli/domain/notice/dto/response/NoticeDetailResponse.java
  src/main/java/com/ilta/solepli/domain/notice/dto/response/NoticePreviewResponse.java
  src/main/java/com/ilta/solepli/domain/notice/entity/Notice.java
  src/main/java/com/ilta/solepli/domain/notice/repository/NoticeRepository.java
  src/main/java/com/ilta/solepli/domain/notice/service/NoticeService.java
  src/main/java/com/ilta/solepli/global/config/SecurityConfig.java
  src/main/java/com/ilta/solepli/global/exception/ErrorCode.java
Labels: Feature ✨

#126 Feat: 장소 상세 정보 조회시 사용자 쏠마크 여부 및 장소 쏠마크 개수 추가 (#118)
  src/main/java/com/ilta/solepli/domain/solmap/controller/SolmapController.java
  src/main/java/com/ilta/solepli/domain/solmap/dto/PlaceDetail.java
  src/main/java/com/ilta/solepli/domain/solmap/service/SolmapService.java
  src/main/java/com/ilta/solepli/domain/solmark/place/repository/SolmarkPlaceRepository.java
Labels: Feature ✨

#129 Refactor: 쏠루트 API 응답 수정 (#127)
  src/main/java/com/ilta/solepli/domain/solroute/controller/SolrouteController.java
  src/main/java/com/ilta/solepli/domain/solroute/dto/response/PlacePreviewResponse.java
  src/main/java/com/ilta/solepli/domain/solroute/dto/response/SolrouteDetailResponse.java
  src/main/java/com/ilta/solepli/domain/solroute/dto/response/SolroutePreviewResponse.java
  src/main/java/com/ilta/solepli/domain/solroute/entity/Solroute.java
  src/main/java/com/ilta/solepli/domain/solroute/entity/SolrouteStatus.java
  src/main/java/com/ilta/solepli/domain/solroute/service/SolrouteService.java
Labels: Refactor ♻️

#130 Fix: 쏠마크 저장 리스트 조회시 장소 개수 불일치 수정 (#128)
  src/main/java/com/ilta/solepli/domain/solmark/place/service/SolmarkPlaceService.java
Labels: Bug 🐞

#132 Fix: CORS 설정에 PATCH 메소드 추가 (#131)
  src/main/java/com/ilta/solepli/global/config/SecurityConfig.java
Labels: Bug 🐞, Security 🔒
