Repository Solepli/Solepli-backend, pull requests merged in 2025-08, with the labels that each got.

#180 Feat: 쏠맵 연관검색어 주소 검색 기능 추가 (#179)
  src/main/java/com/ilta/solepli/domain/solmap/service/SolmapService.java
Labels: Feature ✨, Refactor ♻️

#183 Refactor: Cookie 관련 Setting (#181)
  src/main/java/com/ilta/solepli/domain/auth/service/AuthService.java
  src/main/java/com/ilta/solepli/global/properties/CookieProperties.java
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
Labels: Refactor ♻️, Security 🔒

#185 Refactor: 장소 검색시 검색어 조건에 장소의 주소도 추가(#177)
  src/main/java/com/ilta/solepli/domain/place/controller/PlaceController.java
  src/main/java/com/ilta/solepli/domain/place/entity/SearchType.java
  src/main/java/com/ilta/solepli/domain/place/repository/PlaceRepositoryCustom.java
  src/main/java/com/ilta/solepli/domain/place/repository/PlaceRepositoryImpl.java
  src/main/java/com/ilta/solepli/domain/place/service/PlaceService.java
Labels: Refactor ♻️

#188 Refactor: 동일 제목 쏠루트 저장 시 번호 자동 부여 (#187)
  src/main/java/com/ilta/solepli/domain/solroute/repository/SolrouteRepository.java
  src/main/java/com/ilta/solepli/domain/solroute/service/SolrouteService.java
Labels: Refactor ♻️
