Repository Solepli/Solepli-backend, pull requests merged in 2025-07, with the labels that each got.

#141 Fix: EndpointRequest.to(prometheus)로 actuator prometheus 엔드포인트 인증 없이 허용 (#140)
  src/main/java/com/ilta/solepli/global/config/SecurityConfig.java
Labels: Bug 🐞

#146 Refactor: 쏠루트 관련 DTO PlaceInfo 필드 이름 변경 (#145)
  src/main/java/com/ilta/solepli/domain/solroute/dto/request/SolrouteCreateRequest.java
  src/main/java/com/ilta/solepli/domain/solroute/dto/request/SolroutePatchRequest.java
  src/main/java/com/ilta/solepli/domain/solroute/dto/response/SolrouteDetailResponse.java
  src/main/java/com/ilta/solepli/domain/solroute/service/SolrouteService.java
Labels: Refactor ♻️

#148 Refactor: 장소 검색 응답 DTO 필드 추가 (#147)
  src/main/java/com/ilta/solepli/domain/place/dto/response/PlaceSearchResponse.java
  src/main/java/com/ilta/solepli/domain/place/repository/PlaceRepositoryImpl.java
Labels: Refactor ♻️

#150 Feat: 쏠마크 장소 리스트 조회시 응답 필드값 변경 및 추가 (#149)
  src/main/java/com/ilta/solepli/domain/solmark/place/dto/response/SolmarkPlaceDto.java
  src/main/java/com/ilta/solepli/domain/solmark/place/repository/SolmarkPlaceRepository.java
  src/main/java/com/ilta/solepli/domain/solmark/place/service/SolmarkPlaceService.java
Labels: Feature ✨

#152 Fix: 관리자 회원가입시 닉네임 중복 문제 및 쏠맵 장소의 이미지 없는 리뷰가 조회되지 않는 문제 해결 (#151)
  src/main/java/com/ilta/solepli/domain/review/repository/ReviewRepository.java
  src/main/java/com/ilta/solepli/domain/user/repository/UserRepository.java
Labels: Bug 🐞

#154 Feat: 쏠맵 장소 프리뷰 조회시 사용자의 장소 쏠마크 판별 여부 기능 구현 (#153)
  src/main/java/com/ilta/solepli/domain/solmap/controller/SolmapController.java
  src/main/java/com/ilta/solepli/domain/solmap/dto/PlacePreviewDetail.java
  src/main/java/com/ilta/solepli/domain/solmap/service/SolmapService.java
Labels: Feature ✨

#156 Feat: 소셜 로그인 콜백 URL에 인증 예외 적용 (#155)
  src/main/java/com/ilta/solepli/global/config/SecurityConfig.java
Labels: Feature ✨

#158 Refactor: soft delete 방식을 hard delete 방식으로 변경 (#157)
  src/main/java/com/ilta/solepli/domain/notice/service/NoticeService.java
  src/main/java/com/ilta/solepli/domain/sollect/service/SollectService.java
  src/main/java/com/ilta/solepli/domain/solmark/place/service/SolmarkPlaceService.java
  src/main/java/com/ilta/solepli/domain/solroute/service/SolrouteService.java
  src/main/java/com/ilta/solepli/domain/tag/entity/SoloTag.java
Labels: Refactor ♻️

#160 Refactor: 쏠렉트 상세조회 응답 DTO 필드명 (placeId -> id) 변경 (#159)
  src/main/java/com/ilta/solepli/domain/sollect/dto/response/SollectDetailResponse.java
  src/main/java/com/ilta/solepli/domain/sollect/service/SollectService.java
Labels: Refactor ♻️

#162 Refactor: 쏠루트 - 추가한 장소 근처 인기 장소 조회 DTO 수정 (#161)
  src/main/java/com/ilta/solepli/domain/solroute/controller/SolrouteController.java
  src/main/java/com/ilta/solepli/domain/solroute/dto/response/PlaceSummaryResponse.java
  src/main/java/com/ilta/solepli/domain/solroute/service/SolrouteService.java
Labels: Refactor ♻️

#164 Refactor: 쏠렉트 수정 요청 DTO에 @Valid 추가 (#163)
  src/main/java/com/ilta/solepli/domain/solroute/controller/SolrouteController.java
Labels: Refactor ♻️

#166 Fix: 쏠마크 - 장소 삭제 방식 수정 및 연관검색어 km 소수점 변경 (#165)
  src/main/java/com/ilta/solepli/domain/solmap/dto/Distance.java
  src/main/java/com/ilta/solepli/domain/solmark/place/service/SolmarkPlaceService.java
Labels: Bug 🐞, Refactor ♻️

#170 Refactor: 장소 검색 응답 DTO에 isMarked 필드 추가 (#169)
  src/main/java/com/ilta/solepli/domain/place/controller/PlaceController.java
  src/main/java/com/ilta/solepli/domain/place/dto/response/PlaceSearchResponse.java
  src/main/java/com/ilta/solepli/domain/place/dto/response/PlaceSearchResponseDTO.java
  src/main/java/com/ilta/solepli/domain/place/repository/PlaceRepositoryCustom.java
  src/main/java/com/ilta/solepli/domain/place/repository/PlaceRepositoryImpl.java
  src/main/java/com/ilta/solepli/domain/place/service/PlaceService.java
Labels: Refactor ♻️

#174 Feat: Refresh Token 도입 (#173)
  src/main/java/com/ilta/solepli/domain/auth/controller/AuthController.java
  src/main/java/com/ilta/solepli/domain/auth/filter/JwtAuthenticationFilter.java
  src/main/java/com/ilta/solepli/domain/auth/service/AuthService.java
  src/main/java/com/ilta/solepli/domain/auth/service/JwtTokenProvider.java
  src/main/java/com/ilta/solepli/global/config/SecurityConfig.java
  src/main/java/com/ilta/solepli/global/config/SwaggerConfig.java
  src/main/java/com/ilta/solepli/global/exception/ErrorCode.java
  src/main/java/com/ilta/solepli/global/util/JwtUtil.java
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
Labels: Feature ✨, Security 🔒
